### ISSUE TITLE
'fastrtpsgen -version' just works correctly the second time gradle assembles

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS-Gen#10]
Steps to reproduce:
1. Clone Fast-RTPS-Gen
2. `gradle assemble`
3. Set PATH (`PATH=$PATH..../Fast-RTPS-Gen/scripts`)
4. Running `fastrtpsgen -version` returns:
```console
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
ERROR: Getting version. null
```
5. If issuing `gradle assemble` a second time and running `fasrtpsgen -v`, it now works:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
fastrtpsgen version 1.0.0
```

Is there an explanation for this?

BTW, this is running on a Ubuntu Bionic docker container, with Gradle 5.6.2 and JDK 1.8 installed in it. More specifically: https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_base-bionic

**Comment by TSC21** [comment]
@LuisGP @raquelalvarezbanos looking for your feedback. Thank you

**Comment by TSC21** [comment]
Also, I can't seem to get it to work as well if I do:
```console
$ cp scripts/fastrtpsgen /usr/local/bin/
$ cp share/fastrtps/fastrtpsgen.jar /usr/local/share/fastrtps/
```
as I get the same `ERROR: Getting version. null` problem. And I have `/usr/local/bin` under *PATH*.

**Comment by TSC21** [comment]
An example of this error showing up, where CMake issues the `fastrtpsgen -version` command:
http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/master/106/pipeline#step-95-log-28

**Comment by LuisGP** [comment]
It has been hard to figure out whats was happening, but I think #11 solves the issue.
@TSC21, could you test it too?

**Comment by TSC21** [comment]
Yes I will. Thank you @LuisGP

**Comment by LuisGP** [comment]
> Yes I will. Thank you @LuisGP

Thank you very much.
