### ISSUE TITLE
Empty sequence CDR serialized size

### ISSUE THREAD

**Issue by VasilyFomin** [eProsima/Fast-RTPS-Gen#17]
Hi,
I'd like to clarify the expected behavior for the empty sequences CDR serialized size.

At the moment, the generated code for `getCdrSerializedSize` includes alignment, even if the sequence is empty:

https://github.com/eProsima/Fast-RTPS-Gen/blob/34f0a2534420762348a7c260270a3a246b9cba63/src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg#L387

Looking at the [CORBA v3.3 spec](https://www.omg.org/spec/CORBA/3.3/Interoperability/PDF#G9.69206) there's nothing special about arrays/sequences serialization, and hence my question:

is is the expected behavior to have an extra alignment bytes in case of an empty array or is it a bug?

Thank you,
Vasily.

**Comment by LuisGP** [comment]
Hi @VasilyFomin 

Sequences and arrays are different types. There is no such thing as an empty array. There could be a zero-size array, but in that case, nothing is serialized, and the size will be 0.

Sequences can be empty, but in that case, only the length of the sequence will be serialized (an unsigned long with value 0, added before the call to the `sequence_serialized_size` macro), which must be aligned. The content size will be zero.

https://github.com/eProsima/Fast-RTPS-Gen/blob/34f0a2534420762348a7c260270a3a246b9cba63/src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg#L313

Maybe I'm missing something, in which of both cases do you see an extra alignment?

Best regards.

**Comment by VasilyFomin** [comment]
Hi @LuisGP,
thanks for the quick reply! 

I see the extra alignment happening for the cases, where values are of different size i.e. we have a double sequence, then the produced `getCdrSerializedSize` will have the extra alignment.

For example, given IDL:

```
struct HelloWorld                                                                                                                                                                          
{                                                                                                                                                                                          
    sequence<double> seq;                                                                                                                                                                  
};                                                                                                                                                                                         
``` 

it generates the following function, notice the call to `align(current, 8)` at the end of the sequence's alignment:

```c
size_t HelloWorld::getCdrSerializedSize(const HelloWorld& data, size_t current_alignment)                                                                                                  
{                                                                                                                                                                                          
    (void)data;                                                                                                                                                                            
    size_t initial_alignment = current_alignment;                                                                                                                                          
                                                                                                                                                                                           
                                                                                                                                                                                           
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);                                                                                                      
                                                                                                                                                                                           
    current_alignment += (data.seq().size() * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);                                                                                
                                                                                                                                                                                           
                                                                                                                                                                                           
                                                                                                                                                                                           
    return current_alignment - initial_alignment;                                                                                                                                          
} 
```

**Comment by LuisGP** [comment]
Hi @VasilyFomin,

I see it now! You are right. 
What do you think about this proposal to fix it?

    if (!data.seq().empty())
    {
        current_alignment += (data.seq().size() * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);                                                                                
    }

Something similar (or exactly the same if `data.seq().size() > 0` check is perform) should be done for arrays.

You can create the PR if you want and have time. Else, I'll do it :).

Best regards.

**Comment by VasilyFomin** [comment]
Hi Luis,

Thanks for the confirmation! Please go ahead with the fix, I'm not exactly familiar with the testing procedures you have in place, so I think you'd do it faster.
