### ISSUE TITLE
[Feature request] Set typename by argument

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS-Gen#19]
In a context where standalone FastRTPS communicates with ROS2 FastRTPS, one issue that was reported many times already (ex: https://answers.ros.org/question/319723/use-ros2-fastrtps-with-standalone-fastrtps-programs/ or https://github.com/eProsima/Fast-RTPS/issues/829) is the fact that the generator for the `PubSubTypes` [automatically sets the type naming from scope](https://github.com/eProsima/Fast-RTPS-Gen/blob/master/src/main/java/com/eprosima/fastrtps/idl/templates/RTPSPubSubTypeSource.stg#L71). Since the type naming doesn't match the type naming that ROS2 expects, this requires one to manually set the type naming in order to match the expected one. As an example, https://github.com/PX4/Firmware/blob/master/msg/templates/urtps/Publisher.cpp.em#L104-L109.

Is it possible that we can overwrite the scope name set above with some argument that we can pass when using `fastrtpsgen -example`? If yes, do you have the bandwidth to add that? Or can you add some pointers on how to pass that argument to the `struct`?

**Comment by TSC21** [comment]
@MiguelCompany @richiprosima any pointers are welcomed. Thanks!

**Comment by TSC21** [comment]
Another remark is that changing the scope is not enough as it is expected a naming with a structure like `module.name::parent.name::struct.name_` (with an underscore in the end). So there's need to be a way of defining a custom name if defined globally.

**Comment by TSC21** [comment]
@LuisGP @richiware @MiguelCompany can any of view please give some suggestion here?

**Comment by LuisGP** [comment]
Hello @TSC21 

I don't know if we are going to have time to address this request, we are pretty busy at this moment. Maybe @MiguelCompany can consider it.

In the case we can't, I propose you to study the possibility to add a `--ros2` parameter so the naming is directly generated in the ROS2 way. This parameter should simply put a boolean in the Context, which is globally accessible in the templates.
Another way would be to define `--topic_name` and `--type_name` parameters, as `String` in the Context and if defined, use them instead of the default naming.

I hope this throws a bit of light to you.

Best regards.

**Comment by TSC21** [comment]
> Hello @TSC21
> 
> I don't know if we are going to have time to address this request, we are pretty busy at this moment. Maybe @MiguelCompany can consider it.
> 
> In the case we can't, I propose you to study the possibility to add a `--ros2` parameter so the naming is directly generated in the ROS2 way. This parameter should simply put a boolean in the Context, which is globally accessible in the templates.
> Another way would be to define `--topic_name` and `--type_name` parameters, as `String` in the Context and if defined, use them instead of the default naming.
> 
> I hope this throws a bit of light to you.
> 
> Best regards.

@LuisGP Thank you very much for your feedback! I actually took some time to investigate how everything connect but it certainly gets diffuse when you try to understand how the globals link to the each part of the template, and how to exactly pass that templates as globals and where. If you could give some pointers that would for sure help bring this further and I would take the implementation myself. Thanks!

**Comment by LuisGP** [comment]
> @LuisGP Thank you very much for your feedback! I actually took some time to investigate how everything connect but it certainly gets diffuse when you try to understand how the globals link to the each part of the template, and how to exactly pass that templates as globals and where. If you could give some pointers that would for sure help bring this further and I would take the implementation myself. Thanks!

@TSC21 I'll try to give you these points.
Fast-RTPS-Gen uses `StringTemplate` as templates for code generation. In the file `src/main/java/com/eprosima/fastcdr/idl/generator/TypesGenerator.java` you can see how from a `StringTemplateGroup` instance, `StringTemplate` instances are created.
Once you have a `StringTemplate` instance, you can add attributes to it, for example:
```java
StringTemplate ifcst = stg_.getInstanceOf("interface");
ifcst.setAttribute("ctx", context);
ifcst.setAttribute("parent", ifc.getParent());
ifcst.setAttribute("interface", ifc);
```
Each attribute maps to a Java object, for example, `ctx` will map to the `context`.
The methods of these objects must follow a particular naming to be accessible:
It must start by `is` if it returns a boolean value, and `get` if it returns anything else. Once inside the template, these methods are accessed without that prefix, for example, the method `context.isROS2()` is used inside the template as `ctx.ROS2`.

I really hope this is enough to continue by yourself.

Best regards.

**Comment by TSC21** [comment]
> > @LuisGP Thank you very much for your feedback! I actually took some time to investigate how everything connect but it certainly gets diffuse when you try to understand how the globals link to the each part of the template, and how to exactly pass that templates as globals and where. If you could give some pointers that would for sure help bring this further and I would take the implementation myself. Thanks!
> 
> @TSC21 I'll try to give you these points.
> Fast-RTPS-Gen uses `StringTemplate` as templates for code generation. In the file `src/main/java/com/eprosima/fastcdr/idl/generator/TypesGenerator.java` you can see how from a `StringTemplateGroup` instance, `StringTemplate` instances are created.
> Once you have a `StringTemplate` instance, you can add attributes to it, for example:
> 
> ```java
> StringTemplate ifcst = stg_.getInstanceOf("interface");
> ifcst.setAttribute("ctx", context);
> ifcst.setAttribute("parent", ifc.getParent());
> ifcst.setAttribute("interface", ifc);
> ```
> 
> Each attribute maps to a Java object, for example, `ctx` will map to the `context`.
> The methods of these objects must follow a particular naming to be accessible:
> It must start by `is` if it returns a boolean value, and `get` if it returns anything else. Once inside the template, these methods are accessed without that prefix, for example, the method `context.isROS2()` is used inside the template as `ctx.ROS2`.
> 
> I really hope this is enough to continue by yourself.
> 
> Best regards.

@LuisGP thank you very much! I think the last thing I need to understand is the way of passing an argument given on the CLI to the `StringTemplate`. Maybe add it to the [main `TemplateGroup`](https://github.com/eProsima/Fast-RTPS-Gen/blob/master/src/main/java/com/eprosima/fastrtps/fastrtpsgen.java#L590-L592). And from there I have it available globally on all StringTemplates?

**Comment by LuisGP** [comment]
I'd follow the same way of the already existing arguments in `fastrtpsgen.java`.
In your case, `fastrtpsgen` should parse the argument and pass it to the Context (in the constructor, for example). The Context should provide the `isXXX` method to allow the template to access to the `XXX` value.
As all templates include the context (if I'm not wrong), it should be directly available.
