### ISSUE TITLE
Not correct name in eprosima::fastrtps::TopicDataType subclass

### ISSUE THREAD

**Issue by cvbn127** [eProsima/Fast-RTPS-Gen#21]
std_msgs__String.idl:
```
module std_msgs {
  module msg {
    struct _String {
      string data;
    };
  };
};
```
After generating(```fastrtpsgen std_msgs__String.idl```) we have in std_msgs__StringPubSubTypes.cxx:
```c++
setName("std_msgs::msg::String");
```
but function [MemberDescriptor::is_type_name_consistent()](https://github.com/eProsima/Fast-RTPS/blob/4ec3610181f4bcd0f23c47f2ab0afd6123d22c3e/src/cpp/fastrtps_deprecated/types/MemberDescriptor.cpp#L383) returns **false** if name contains ':'. So DynamicTypeBuilder fails to build DynamicType_ptr.

**Comment by LuisGP** [comment]
Hi @cvbn127 

Currently, DynamicTypes doesn't allow scope in the name of the type. This is a know limitation that we want to address when we have some time for it.
Do you need to use dynamic types?
Seems that you are using a `ROS2` type, if you don't need DynamicData, you can simply use the static types and should work.

**Comment by cvbn127** [comment]
Hi @LuisGP 
Actually, i just want to use soss-dds for publishing dds messages to Ros2 and DynamicData is used by soss-dds.

**Comment by LuisGP** [comment]
The type used by SOSS-DDS (master branch, I guess) must be defined in the YAML file changing any slash `/` in the ROS2 type by two underscores `__`.

You can see an example [here](https://github.com/eProsima/SOSS-DDS/blob/master/dds/sample/udp/dds_ros2.yaml).

In that way, the DynamicType will be named without illegal characters.

You don't need to use the ROS2 IDL file neither Fast-RTPS-Gen.

**Comment by cvbn127** [comment]
ok, but what if i need to send custom message from dds to ros2?

I have one custom.idl, build it with colcon and can publish/subscribe/use with soss.  
But then i need code for dds. I use for generating Fast-RTPS-Gen and got this issue.

Am i doing something wrong ?

**Comment by LuisGP** [comment]
Using the master branch, you must replicate your custom message using the YAML syntax. You can skip the Fast-RTPS-Gen step.

**Comment by cvbn127** [comment]
soss-dds works fine, i no have troubles with him.  But I need an application, which will publish my custom dds message. Code for this application i should generate from Idl.

**Comment by LuisGP** [comment]
Ok, I think I see the problem now.

To confirm it, you can send me the YAML file used by SOSS.

Fast-RTPS-Gen is generating your type with the scoped name, which isn't allowed by DynamicType. Then your YAML file is referring to that scoped name and then error arises.
To fix it, you should rename your generated type to one which doesn't contain the forbidden characters and change the name in the YAML file too to match it. That should do the trick.

You can see #19 where another user is trying to provide Fast-RTPS-Gen with an argument to allow direct renaming of the type.

**Comment by cvbn127** [comment]
You are right that 'Fast-RTPS-Gen is generating your type with the scoped name, which isn't allowed by DynamicType'.
Sending messages with this type from DDS causes SOSS-DDS not to forward such messages to Ros2.
Of course, after I manually changed the generated code, everything began to work fine.

I see two possible solutions.
You can change the generator so that it generates the type name with underscores (or let the user specify the type name during generation, as suggested in https://github.com/eProsima/Fast-RTPS-Gen/issues/19). And anyone will be able to use Fast-RTPS-Gen together with SOSS-DDS without changing the code manually.
Or you can allow the ':' to be a valid character for DynamicType. Then the user will be able to specify the type with ':' in the configuration file for SOSS-DDS.

**Comment by LuisGP** [comment]
> You are right that 'Fast-RTPS-Gen is generating your type with the scoped name, which isn't allowed by DynamicType'.
> Sending messages with this type from DDS causes SOSS-DDS not to forward such messages to Ros2.
> Of course, after I manually changed the generated code, everything began to work fine.
> 
> I see two possible solutions.
> You can change the generator so that it generates the type name with underscores (or let the user specify the type name during generation, as suggested in #19). And anyone will be able to use Fast-RTPS-Gen together with SOSS-DDS without changing the code manually.
> Or you can allow the ':' to be a valid character for DynamicType. Then the user will be able to specify the type with ':' in the configuration file for SOSS-DDS.

It's very likely that both solutions will be implemented soon.

I'm closing this issue, feel free to reopen it or create a new one if you find another problem.
Thank you very much.
