### ISSUE TITLE
fastrtpsgen generates fixed getMaxCdrSerializedSize for strings and sequences

### ISSUE THREAD

**Issue by topin89** [eProsima/Fast-RTPS-Gen#29]
Let's take a look at HelloWorld.idl

```
struct HelloWorld
{
    string msg;
    char a[1024];
    sequence<char> msg2;
};
```

And now let's take a look at getMaxCdrSerializedSize

```
size_t HelloWorld::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    // probably string, implicitly 255 bytes plus probably '\0'
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    // definitely char array
    current_alignment += ((1024) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    // probably vector size
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    // probably vector itself, max 100 elements
    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    return current_alignment - initial_alignment;
}
```

That's called only in HelloWorldPubSubType

```
HelloWorldPubSubType::HelloWorldPubSubType()
{
    setName("HelloWorld");
    m_typeSize = static_cast<uint32_t>(HelloWorld::getMaxCdrSerializedSize()) + 4 /*encapsulation*/;
    ... 
}
```

Since there are these lines about m_typeSize in a doxygen

> Maximum serialized size of the type in bytes.
> If the type has unbounded fields, and therefore cannot have a maximum size, use 0.

I suppose codegen is a bit outdated or there is another reason I know nothing about.

Please clarify if it's an error or not, will it be fixed soon or not, should I bother with PR if you have more important things to do or not.

**Comment by LuisGP** [comment]
Hi @topin89 

`getMaxCdrSerializedSize` is intended to be used to provide to `PREALLOCATED` memory policies an estimation of the maximum size of the type.

Unbounded `string`, `sequence`, and `map`, doesn't have a maximum size, so `getMaxCdrSerializedSize` must make a decision based on common cases vs. memory requirement. This decision is `255` for strings and `100` for sequences and maps.

This is an internal requirement to have meaning to a maximum size or 0.

If these default maximum sizes aren't enough for your use case, you can solve it in two ways:

- Don't use PREALLOCATED memory policy. A dynamic memory policy will calculate the needed size by calling to `getCdrSerializedSize`.

- Establish your own bounds. For example `string<5000> msg;` and `sequence<char, 1024> msg2;`

Best regards.

**Comment by topin89** [comment]
Thanks!
