### ISSUE TITLE
Problem when deserializing nested maps

### ISSUE THREAD

**Issue by pbustos** [eProsima/Fast-RTPS-Gen#30]
Hello, 

I am sending a nested map using the 
https://github.com/eProsima/Fast-RTPS-Gen/tree/feature/complex_key_map branch that was provided a few days ago to allow strings as keys in maps.

The structure is: 

```idl
  struct DotKernel {
        map<long, string> ds;
    };
    struct AworSet {
        long id;
        DotKernel dk;
    };
    struct OrMap {
        long id;
        map<long, AworSet> m;
    };
```

and after it is sent and deserialized,  data  has duplicated map values. 

These are the structures sent and received:

sent: OrMap:  
 id: 0
Map: 0->AworSet: ID:[0], Data: [1804289383-->prueba, ] 
1->AworSet: ID:[1], Data: [846930886-->prueba, ] 

received: OrMap:  
 id: 0
Map: 0->AworSet: ID:[0], Data: [1804289383-->prueba, ] 
1->AworSet: ID:[1], Data: [846930886-->prueba, 1804289383-->prueba, ]

To reproduce: 

1. save the nested map as prueba.idl
2. fastrtpsgen prueba.idl -example CMake 
3. Add this code to send the map:

```c++
  std::map<int32_t, AworSet> nodes;
    int x = 2;
    for (int i = 0 ; i < x; ++i)
    {
        AworSet set;
        set.id(i);
        DotKernel dk;
        std::map<int, std::string> ds;
        ds.insert(std::make_pair(rand(), "prueba"));
        dk.ds(ds);
        set.dk(dk);
        nodes.insert(std::make_pair(i,set));
    }
    OrMap st;
    st.id(0);
    st.m(nodes);

    std::cout << "sent: " << st << std::endl;
    mp_publisher->write(&st);
```

We think that the problem might be in this method:

```c++
   template<class _K, class _T>
                    Cdr& deserialize(std::map<_K, _T> &map_t)
                    {
                        uint32_t seqLength = 0;
                        state state_(*this);

                        *this >> seqLength;
   
                        try
                        {
                            //map_t.resize(seqLength);
                            _K key;
                            _T value;
                            for (uint32_t i = 0; i < seqLength; ++i)
                            {
                                *this >> key;
                                *this >> value;
                                map_t.emplace(std::pair<_K, _T>(key, value));
                            }
                            //return deserializeArray(vector_t.data(), vector_t.size());
                        }
                        catch(eprosima::fastcdr::exception::Exception &ex)
                        {
                            setState(state_);
                            ex.raise();
                        }

                        return *this;
                    }
```

It looks like the variable value is re-used when the maps are nested.

Thanks a lot.

**Comment by LuisGP** [comment]
Hi @pbustos 

Seems you're right. Did you try moving `_K key;` and `_T value;` inside the loop?

Best regards.

**Comment by pbustos** [comment]
Yes and it is working. Thanks.

Are these changes going to be in the stable branch?

Best regards.

**Comment by LuisGP** [comment]
I just created the PR, I hope it doesn't take much time to merge.
