### ISSUE TITLE
fastrtpsgen -version returns 0.0.0 [6488]

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS-Gen#4]
After building using `gradle assemble` and copied both `fastrtpsgen` script and `fastrtpsgen.jar` to `/usr/local/bin/` and `/usr/local/share/fastrtps/` respectively, using `fastrtpsgen -version` returns:
```sh
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
fastrtpsgen version 0.0.0
```

**Comment by TSC21** [comment]
@raquelalvarezbanos @LuisGP any recommendation here? Maybe some source code error?

**Comment by TSC21** [comment]
It looks like https://github.com/eProsima/Fast-RTPS-Gen/blob/master/build.gradle#L44 is not creating a `version` file on build. At least looking at `build/resources/main/` I can only find the `com` directory.

**Comment by TSC21** [comment]
Also, I think I understand as well why is this not setting the version correctly: https://github.com/eProsima/Fast-RTPS/blob/1.7.x/cmake/dev/java_support.cmake#L32. We are not even passing the version of Fast-RTPS here. Should this be automated according to the release of Fast-RTPS installed on ones system, or should this be set automatically? I don't think it makes sense one having to set `-Pcustomversion=` everytime it wants to setup the package version.

Right now I find three different issues:
1. `assemble` doesn't create a `version` file under `resources/main/;
2. `-Pcustomversion=` is not setup, which defaults the version property to `0.0.0`;
3. unrelated: `gradle build` gets stuck on 85% forever:
```sh
<===========--> 85% EXECUTING [10m 03s]
> :test > 0 tests completed
> :test > Executing test test.com.eprosima.fastrtps.FastRTPSGenTest
```

**Comment by TSC21** [comment]
**Note:** using `gradle assemble -Pcustomversion=x.x.x` creates the version file correctly. But again, we should have a way of automate this according to the release (considering you want to keep the Fast-RTPS-Gen release synced with the Fast-RTPS release).

**Comment by TSC21** [comment]
OK, never mind the past two comments regarding the file creation. Seems like it still works but sets it to 0.0.0 if the parameter is not passed on build. Still, we have the issue on the version setup.

**Comment by LuisGP** [comment]
Hi @TSC21

Thank you for reporting this issue with versioning. We added a `version_str` in the `build.gradle` file to keep track of the current version.
As fastrtpsgen is no longer part of Fast-RTPS, the versioning is going to be reset to `1.0.0` to be congruent with the GitHub's versioning.

I'm creating a PR solving both issues.

**Comment by LuisGP** [comment]
#5 Should fix all issues reported here. @TSC21 could you test it?

**Comment by TSC21** [comment]
`fastrtpsgen -version` does work as it should now:
```sh
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
fastrtpsgen version 1.0.0
```

**Comment by LuisGP** [comment]
> @LuisGP `gradle build` gets stuck, but now on 88%.

Please, take into account that it downloads and compiles Fast-RTPS and performs testing against a bunch of processed IDL files.
I just tested again and it took 9 minutes and 12 seconds in a i7-8750H processor.
You can speed up the compilation step adding -jX in line 48 of the file FastRTPSGenTest.java, being X the number of cores of your processor (typically 8 or 12).

    commands.add(new String[]{"make -j12 install, OUTPUT_PATH + "/Fast-RTPS/build"});

**Comment by LuisGP** [comment]
I'm closing this issue since #5 and #6 should solve (and improve) it.
Feel free to reopen it if you have any related questions or issues.
